version: 2

defaults: &defaults
  machine: true
  working_directory: ~/project

aliases:
  - &build-docker
    name: Build Docker Image
    command: |
      docker build -t avegorov/docker-react-native-android .
      docker run --rm --name rn-env avegorov/docker-react-native-android bin/sh -c "npx envinfo"

jobs:
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: *build-docker
      - run:
          name: Deploy docker
          command: |
            source ~/.bashrc
            nvm i node
            node publish_docker.js

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
